apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardinality-bomb
  labels:
    app: cardinality-bomb
    kubernetes.azure.com/generator: draft
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardinality-bomb
  template:
    metadata:
      labels:
        app: cardinality-bomb
    spec:
      containers:
        - name: cardinality-bomb
          image: paulgmiller/cardinality-bomb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
